.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.TH debgtd 1
.SH NAME
debgtd \- a tool to help organise and prioritise your Debian bugs
.SH SYNOPSIS
.B debgtd
.SH DESCRIPTION
.B debgtd
("getting things done") is a GUI tool which allows you
to visualise, sort and filter a list of bugs from the Debian
Bug Tracker (BTS).
.PP
debgtd is intended to help users contribute to Debian by
keeping track of which bugs they have submitted and determine
which need more the user's attention (such as requiring more
information, etc.)
.PP
Place the e-mail address that you use to report bugs into the 
text field at the top of the
.B debgtd
window and click the adjacent button to populate the list.
.PP
If you define the
.B DEBEMAIL
environment variable prior to invoking debgtd, it will auto-populate
the text field.
.SH FILES
.B debgtd
honours the XDG desktop specification. By default, data files are
kept at
.B ~/.local/share/debgtd
, but you can override this location by defining the
.B XDG_DATA_HOME
environment variable.
.SH BUGS
debgtd is in an early stage of development.  If you find a bug, please
check to see if it has been reported at 
.URL "http://www.debian.org/Bugs/" "the Debian Bug Tracking System"
.
.SH GET INVOLVED
debgtd is written to be a useful tool for workflow. Comments and
suggestions and patches to the author are very welcome.
.SH SEE ALSO
reportbug(1),
bts(1),
sensible-browser(1).
.SH AUTHOR
Jon Dowland <jon@alcopop.org>.
