.TH debgtd 1
.SH NAME
debgtd \- a tool to help organise and prioritise your Debian bugs
.SH SYNOPSIS
.B debgtd
.SH DESCRIPTION
.B debgtd
("getting things done") is a GUI tool which allows you
to visualise, sort and filter a list of bugs from the Debian
Bug Tracker (BTS).
.PP
debgtd is intended to help users contribute to Debian by
keeping track of which bugs they have submitted and determine
need more the user's attention (such as requiring more
information, etc.)
.SH INVOCATION
Before invoking debgtd, please ensure that the environment variable
.I DEBEMAIL
is defined to the e-mail address you use to report bugs to the Debian
Bug Tracking System.
.SH BUGS
debgtd is in an early stage of development. A list of known bugs
can be found in /usr/share/doc/debgtd/BUGS.
.SH GET INVOLVED
debgtd is written to be a useful tool for workflow. Comments and
suggestions and patches to the author are very welcome.
.SH SEE ALSO
reportbug(1),
bts(1),
x-www-browser(1).
.SH AUTHOR
Jon Dowland <jon@alcopop.org>.
